import React from "react";
import {
  Container,
  Typography,
  Box,
  Button,
  List,
  ListItem,
  ListItemText,
} from "@mui/material";
import { useNavigate } from "react-router-dom";

const Terms: React.FC = () => {
  return (
    <Container sx={{ mt: 8, mb: 8 }}>
      <Typography variant="h3" component="h1" gutterBottom>
        Stringscribe – Terms of Service
      </Typography>
      <Typography variant="h4" component="h2" gutterBottom>
        Effective Date: August 01, 2025
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        These Terms of Service (“Terms”) govern your use of Stringscribe’s
        audio-to-sheet-music tool (“Service”). By uploading any file to
        Stringscribe, you agree to be bound by these Terms. If you do not agree,
        do not use the Service.
      </Typography>
      <Typography variant="h4" component="h2" gutterBottom>
        1. Eligibility & Ownership of Content
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        You may only upload audio files to which:
      </Typography>
      <List dense>
        <ListItem>
          <ListItemText>(a) You own all rights, or</ListItemText>
        </ListItem>
        <ListItem>
          <ListItemText>
            (b) You have obtained all necessary permissions from the copyright
            owner(s) to use the content in this way.
          </ListItemText>
        </ListItem>
      </List>
      <Typography variant="body2" component="p" gutterBottom>
        By uploading, you affirm that your use does not infringe any third-party
        rights, including copyrights.
      </Typography>
      <Typography variant="h4" component="h2" gutterBottom>
        2. Permitted Use of Outputs
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        Any sheet music or related output generated by the Service is provided
        for personal, non-commercial use only, unless you hold all necessary
        rights to the underlying composition. You are solely responsible for
        determining whether your use of the output is lawful.
      </Typography>
      <Typography variant="h4" component="h2" gutterBottom>
        3. User Responsibility and Liability
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        You understand and agree that
      </Typography>
      <List dense>
        <ListItem>
          <ListItemText>
            (a) You are solely responsible for the content you upload and any
            resulting use of the outputs.
          </ListItemText>
        </ListItem>
        <ListItem>
          <ListItemText>
            (b) Stringscribe assumes no liability for any copyright infringement
            or misuse of generated outputs.
          </ListItemText>
        </ListItem>
        <ListItem>
          <ListItemText>
            (c) You agree to indemnify and hold harmless Stringscribe, its
            owners, and affiliates from any claims arising out of your use of
            the Service.
          </ListItemText>
        </ListItem>
      </List>
      <Typography variant="h4" component="h2" gutterBottom>
        4. Processing and Storing of Files
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        Uploaded files may be temporarily stored and processed to generate
        results. Stringscribe does not claim ownership of your uploaded files or
        generated outputs. Files may be deleted automatically after processing.
      </Typography>
      <Typography variant="h4" component="h2" gutterBottom>
        5. Prohibited Content
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        You may not upload content that:
      </Typography>
      <List dense>
        <ListItem>
          <ListItemText>(a) Is illegal under applicable laws</ListItemText>
        </ListItem>
        <ListItem>
          <ListItemText>(b) Infringes upon third-party right</ListItemText>
        </ListItem>
        <ListItem>
          <ListItemText>(c) Contains malicious software or code</ListItemText>
        </ListItem>
      </List>
      <Typography variant="h4" component="h2" gutterBottom>
        6. Accuracy of Outputs
      </Typography>
      <Typography variant="body2" component="p" gutterBottom>
        You acknowledge that Stringscribe uses AI-based processing, and outputs
        may be inaccurate, incomplete, or require manual correction. The Service
        makes no guarantee of accuracy or fitness for a specific purpose.
      </Typography>
    </Container>
  );
};

export default Terms;
