import React from "react";
import {
  Container,
  Typography,
  Box,
  Button,
  List,
  ListItem,
  ListItemText,
} from "@mui/material";

// simple page displaying TOS

const Terms: React.FC = () => {
  const h4Style = {
    color: "#667eea",
    fontWeight: 600,
    borderBottom: "2px solid rgba(102, 126, 234, 0.2)",
    pb: 1,
    mb: 3,
  };
  return (
    <Container maxWidth="md" sx={{ mt: 8, mb: 8 }}>
      <Box sx={{ textAlign: "center", mb: 6 }}>
        <Typography
          variant="h2"
          component="h1"
          color="#667eea"
          gutterBottom
          sx={{
            fontWeight: 700,
            mb: 2,
          }}
        >
          String Scribe – Terms of Service
        </Typography>
        <Typography
          variant="h5"
          component="h2"
          color="text.secondary"
          sx={{ fontWeight: 400 }}
        >
          Effective Date: August 01, 2025
        </Typography>
      </Box>
      <Typography
        variant="body1"
        component="p"
        gutterBottom
        sx={{
          lineHeight: 1.7,
          maxWidth: 800,
          mx: "auto",
          mb: 4,
          textAlign: "center",
        }}
      >
        These Terms of Service ("Terms") govern your use of Stringscribe's
        audio-to-sheet-music tool ("Service"). By uploading any file to
        Stringscribe, you agree to be bound by these Terms. If you do not agree,
        do not use the Service.
      </Typography>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h2" gutterBottom sx={h4Style}>
          1. Eligibility & Ownership of Content
        </Typography>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ mb: 2, lineHeight: 1.7 }}
        >
          You may only upload audio files to which:
        </Typography>
        <Box sx={{ display: "flex", justifyContent: "center", mb: 3 }}>
          <List dense sx={{ maxWidth: 600 }}>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(a) You own all rights, or"
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(b) You have obtained all necessary permissions from the copyright owner(s) to use the content in this way."
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
          </List>
        </Box>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ lineHeight: 1.7 }}
        >
          By uploading, you affirm that your use does not infringe any
          third-party rights, including copyrights.
        </Typography>
      </Box>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h2" gutterBottom sx={h4Style}>
          2. Permitted Use of Outputs
        </Typography>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ lineHeight: 1.7 }}
        >
          Any sheet music or related output generated by the Service is provided
          for personal, non-commercial use only, unless you hold all necessary
          rights to the underlying composition. You are solely responsible for
          determining whether your use of the output is lawful.
        </Typography>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h2" gutterBottom sx={h4Style}>
          3. User Responsibility and Liability
        </Typography>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ mb: 2, lineHeight: 1.7 }}
        >
          You understand and agree that
        </Typography>
        <Box sx={{ display: "flex", justifyContent: "center", mb: 3 }}>
          <List dense sx={{ maxWidth: 600 }}>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(a) You are solely responsible for the content you upload and any resulting use of the outputs."
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(b) Stringscribe assumes no liability for any copyright infringement or misuse of generated outputs."
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(c) You agree to indemnify and hold harmless Stringscribe, its owners, and affiliates from any claims arising out of your use of the Service."
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
          </List>
        </Box>
      </Box>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h2" gutterBottom sx={h4Style}>
          4. Processing and Storing of Files
        </Typography>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ lineHeight: 1.7 }}
        >
          Uploaded files may be temporarily stored and processed to generate
          results. Stringscribe does not claim ownership of your uploaded files
          or generated outputs. Files may be deleted automatically after
          processing.
        </Typography>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h2" gutterBottom sx={h4Style}>
          5. Prohibited Content
        </Typography>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ mb: 2, lineHeight: 1.7 }}
        >
          You may not upload content that:
        </Typography>
        <Box sx={{ display: "flex", justifyContent: "center", mb: 3 }}>
          <List dense sx={{ maxWidth: 600 }}>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(a) Is illegal under applicable laws"
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(b) Infringes upon third-party right"
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
            <ListItem sx={{ py: 0.5 }}>
              <ListItemText
                primary="(c) Contains malicious software or code"
                sx={{ "& .MuiListItemText-primary": { lineHeight: 1.6 } }}
              />
            </ListItem>
          </List>
        </Box>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h2" gutterBottom sx={h4Style}>
          6. Accuracy of Outputs
        </Typography>
        <Typography
          variant="body1"
          component="p"
          gutterBottom
          sx={{ lineHeight: 1.7 }}
        >
          You acknowledge that Stringscribe uses AI-based processing, and
          outputs may be inaccurate, incomplete, or require manual correction.
          The Service makes no guarantee of accuracy or fitness for a specific
          purpose.
        </Typography>
      </Box>
    </Container>
  );
};

export default Terms;
